version: '3.7'

services:  
  db_contabil:
    container_name: db_contabil
    image: postgres:15.4
    environment:
      - POSTGRES_DB=contabil
      - POSTGRES_USER=contabil
      - POSTGRES_PASSWORD=contabil
      - PGDATA=/data/postgres
    volumes:
      - ./db/v_db_contabil:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: always
  
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: contabil
      RABBITMQ_DEFAULT_PASS: contabil
    networks:
      - rabbitmq

  contabil-ms:
    container_name: contabil-ms
    build: ./contabil-ms/
    restart: always
    ports:
      - "80:8080"
    networks:
      - db
      - rabbitmq
      - app
    depends_on:
      - db_contabil
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
  db:
    driver: bridge
  app:
    driver: bridge